language: node_js
node_js:
  - "9"
dist: trusty
addons:
  chrome: stable
sudo: false
branches:
  only:
  - master
before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
before_script:
  - npm install -g @angular/cli
script:
- ng lint
- npm run test-headless
- ng build --prod --base-href https://t-palmer.github.io/travis-demo/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/travis-demo
  on:
    branch: master
    